// Foxy, the world's chat mascot — replies generated by a small local
// instruction model (transformers.js, CPU, no external API). Same lazy-load
// pattern as aiTranslate: the model downloads on first use, then is cached, so
// the server boots instantly and only pays the cost when someone talks to Foxy.
const MODEL = 'Xenova/LaMini-Flan-T5-77M';

// Flan-T5 sometimes emits the generic assistant disclaimer — swap those (and
// empty answers) for an in-character Foxy line.
const FALLBACKS = [
  "Yip! I'm Foxy — ask me about words or phrases and I'll help!",
  "Woof! My name is Foxy. What would you like to learn today?",
  "*wags tail* I'm Foxy, your language fox. Try asking me how to say something!",
];
function foxify(text, seed) {
  const t = (text || '').trim();
  if (!t || /as an ai|language model|i (do not|don't) have|i cannot|i can't (form|provide)/i.test(t)) {
    return FALLBACKS[Math.abs(seed) % FALLBACKS.length];
  }
  return t;
}

let transformersPromise = null;
let genPromise = null;

async function getGen() {
  if (!genPromise) {
    genPromise = (async () => {
      if (!transformersPromise) transformersPromise = import('@huggingface/transformers');
      const { pipeline } = await transformersPromise;
      return pipeline('text2text-generation', MODEL);
    })();
    genPromise.catch(() => { genPromise = null; }); // don't cache a failed load
  }
  return genPromise;
}

export async function foxyReply(message) {
  const clean = String(message || '').replace(/@[Ff]oxy/g, '').slice(0, 300).trim();
  if (!clean) return 'Yip! Ask me something and I will do my best to answer.';
  const gen = await getGen();
  // Give Foxy a persona; LaMini-Flan-T5 is instruction-tuned, so the output is
  // just the answer (it doesn't echo the prompt).
  const prompt = `Foxy is a friendly, playful pet fox who loves helping people learn languages. `
    + `Foxy always answers in one or two short, warm sentences and never says it is an AI. `
    + `Write Foxy's reply to this message: "${clean}"`;
  const out = await gen(prompt, { max_new_tokens: 80, temperature: 0.7, do_sample: true, repetition_penalty: 1.3 });
  const text = (Array.isArray(out) ? out[0] : out)?.generated_text || '';
  let seed = 0;
  for (let i = 0; i < clean.length; i++) seed = (seed * 31 + clean.charCodeAt(i)) | 0;
  return foxify(text, seed);
}

export function isFoxyReady() { return !!genPromise; }
